title: <p align="center"> Naga Gayathri </p>
logo: /assets/Gayi1.png
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  Also handing the VBA Projects.
  Worked with Accenture as Associate .
  Working in Northern Trust for 4 years.
  <br>
  </p>



theme: jekyll-theme-minimal
